fix: version pin to support 0.13
cloudposse/terraform-aws-vpc-flow-logs-s3-bucket pull request #12
Opened 2020-10-26 19:45 UTC by dotCipher

_See https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/10 for base changelog_

## what
* Add new test to make build green
* Minor tweaks to makefile

## why
* The automated PR from https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/10 was red 😄 

## references
* https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/10

2020-10-26 19:50 UTC, Gowiem requested changes

2020-10-26 19:50 UTC, Gowiem commented on versions.tf
> +  required_version = ">= 0.12.0, < 0.14.0"
@dotCipher We are no longer pinning upper bound versions as it's very likely that our modules will work with 0.14 when it comes out. Just pin the lower bound version (`>= 0.12.0`) and we'll be good.

2020-10-26 19:50 UTC, Gowiem commented on versions.tf
>      aws      = "~> 2.0"
@dotCipher while you making updates -- Mind changing the requires_providers to  `>=` instead of `~>`?

2020-10-26 19:50 UTC, Gowiem commented on test/src/examples_complete_test.go
> +	expectedBucketArn := fmt.Sprintf("arn:aws:s3:::%s-%s-%s", varNamespace, varStage, varName)
You're passing an attribute into `Options` and then not accounting for it here. Not sure if it will work or not, but let's see!

2020-10-26 19:50 UTC, Gowiem commented
/test all

2020-10-26 20:02 UTC, dotCipher commented on test/src/examples_complete_test.go
> +	expectedBucketArn := fmt.Sprintf("arn:aws:s3:::%s-%s-%s", varNamespace, varStage, varName)
Oh right, where's the place it gets picked up? That attribute automatically known by the s3 module?

2020-10-26 20:02 UTC, dotCipher commented on versions.tf
>      aws      = "~> 2.0"
Will do, thanks

2020-10-26 21:01 UTC, dotCipher commented
/test all

2020-10-26 21:29 UTC, Gowiem requested changes

2020-10-26 21:31 UTC, Gowiem commented
/test all

2020-10-26 21:35 UTC, Gowiem commented
/rebuild-readme

2020-10-26 21:36 UTC, Gowiem commented
/test all

2020-10-27 01:35 UTC, Gowiem commented
/test all

2020-10-27 01:38 UTC, Gowiem commented
/terraform-fmt

2020-10-27 01:44 UTC, Gowiem commented
/test all

2020-10-27 01:45 UTC, Gowiem approved these changes

2020-10-27 01:46 UTC, Gowiem commented
/rebuild-readme

2020-10-27 02:01 UTC, Gowiem commented
/test all

2020-10-27 02:01 UTC, Gowiem approved these changes

2020-10-27 14:18 UTC, merged