Add 3 new input vars for make vulnerability-free buckets
cloudposse/terraform-aws-vpc-flow-logs-s3-bucket pull request #47
Opened 2022-06-23 02:39 UTC by bcarranza

## what
* Add 3 news input vars 
- versioning_enabled
- acl
- s3_object_ownership

* Upgrade to version `0.28.0` of the s3 log storage module to include the `s3_object_ownership` field.

## why
* Avoid prowler vulnerabilities in scenarios where we do not need to use acls and want the bucket to be modified only by the bucket owner.
* More detail in this issue: https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/issues/46

## references
* Violations overcome thanks to this pr
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.4">
</head>
<body>

Result | Severity | AccountID | Region | Compliance | Service | CheckID | Check Title | Check Output | CIS Level | CAF Epic | Risk | Remediation | Docs | Resource ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PASS | Medium | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.172 | [extra7172] Check if S3 buckets have ACLs enabled | us-west-2: Bucket xxxx-x2-ops-vpc-aws-flow-log has bucket ACLs disabled! | Extra | Logging and Monitoring | S3 ACLs are a legacy access control mechanism that predates IAM. IAM and bucket policies are currently the preferred methods. | Ensure that S3 ACLs are disabled (BucketOwnerEnforced). Use IAM policies and bucket policies to manage access. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Medium | xxxx | us-west-2 | Software and Configuration Checks | s3 | 7.18 | [extra718] Check if S3 buckets have server access logging enabled | us-west-2: Bucket xxxx-x2-ops-vpc-aws-flow-log has server access logging enabled | Extra | Logging and Monitoring | Server access logs can assist you in security and access audits; help you learn about your customer base; and understand your Amazon S3 bill. | Ensure that S3 buckets have Logging enabled. CloudTrail data events can be used in place of S3 bucket logging. If that is the case; this finding can be considered a false positive. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Medium | xxxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.25 | [extra725] Check if S3 buckets have Object-level logging enabled in CloudTrail | us-west-2: S3 bucket xxxx-x2-ops-vpc-aws-flow-log has Object-level logging enabled in trail arn:aws:cloudtrail:us-west-2:xxxxx:trail/x2-ops-cloudtrail-cloudwatch-alarms | Extra | Logging and Monitoring | If logs are not enabled; monitoring of service use and threat analysis is not possible. | Enable logs. Create an S3 lifecycle policy. Define use cases; metrics and automated responses where applicable. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Critical | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.3 | [extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user | us-west-2: xxxx-x2-ops-vpc-aws-flow-log bucket is not Public | Extra | Data Protection | Even if you enable all possible bucket ACL options available in the Amazon S3 console the ACL alone does not allow everyone to download objects from your bucket. Depending on which option you select any user could perform some actions. | You can enable block public access settings only for access points; buckets; and AWS accounts. Amazon S3 does not support block public access settings on a per-object basis. When you apply block public access settings to an account; the settings apply to all AWS Regions globally. The settings might not take effect in all Regions immediately or simultaneously; but they eventually propagate to all Regions. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Medium | xxx | us-west-2 | ens-mp.info.3.s3.1 | s3 | 7.34 | [extra734] Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it | us-west-2: Bucket xxx-x2-ops-vpc-aws-flow-log is enabled for default encryption with aws:kms | Extra | Data Protection | Amazon S3 default encryption provides a way to set the default encryption behavior for an S3 bucket. This will ensure data-at-rest is encrypted. | Ensure that S3 buckets has encryption at rest enabled. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Medium | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.63 | [extra763] Check if S3 buckets have object versioning enabled | us-west-2: Bucket xxxxx-x2-ops-vpc-aws-flow-log has versioning enabled | Extra | Data Protection | With versioning; you can easily recover from both unintended user actions and application failures. | Configure versioning using the Amazon console or API for buckets with sensitive information that is changing frecuently; and backup may not be enough to capture all the changes. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Medium | xxxxx | us-west-2 | ens-mp.com.2.aws.s3.1 | s3 | 7.64 | [extra764] Check if S3 buckets have secure transport policy | us-west-2: Bucket xxxxx-x2-ops-vpc-aws-flow-log has S3 bucket policy to deny requests over insecure transport | Extra | Data Protection | If HTTPS is not enforced on the bucket policy; communication between clients and S3 buckets can use unencrypted HTTP. As a result; sensitive information could be transmitted in clear text over the network or internet. | Ensure that S3 buckets has encryption in transit enabled. |   | xxxxx-x2-ops-vpc-aws-flow-log
PASS | Critical | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.71 | [extra771] Check if S3 buckets have policies which allow WRITE access | us-west-2: Bucket xxxxx-x2-ops-vpc-aws-flow-log has S3 bucket policy which does not allow public write access | Extra | IAM | Non intended users can put objects in a given bucket. | Ensure proper bucket policy is in place with the least privilege principle applied. |   | xxxxxx-x2-ops-vpc-aws-flow-log

</body>
</html>

2022-06-23 02:54 UTC, bcarranza commented
I've created a pr: https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/47

2022-06-24 22:56 UTC, bcarranza commented
Hi Community, what kind of permission we nee to have in the fork repository to grant `Auto Format process`
could you help me please?

2022-10-22 23:07 UTC, Nuru requested changes
We want to maintain backward compatibility, so we need to change the default value of `versioning_enabled` to `false`.

2022-10-22 23:07 UTC, Nuru commented on variables.tf
> +  default     = true
```suggestion
  default     = false
```

2022-10-22 23:08 UTC, Nuru commented on main.tf
> +  version = "0.28.0"
This upgrade is unsafe (significant risk of data loss). 
```suggestion
  version = "1.0.0"
```

2022-10-22 23:15 UTC, Nuru commented
@bcarranza To move this along, I am going to merge these changes into another branch and modify it from there. Thank you for your contribution!

2022-10-22 23:16 UTC, Nuru approved these changes
Will need some changes, but will make on the destination branch.

2022-10-22 23:17 UTC, merged